package com.pactera.gcw.common;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.ui.ModelMap;

import com.google.common.base.Predicate;
import com.google.common.base.Predicates;

import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket createRestApi() {
        return new Docket(DocumentationType.SWAGGER_2)
        			.ignoredParameterTypes(ModelMap.class)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.pactera.gcw"))
                .paths(apiPaths())
                .build();
    }

    @SuppressWarnings("unchecked")
	private Predicate<String> apiPaths() {
        return Predicates.or(PathSelectors.regex("/.*"));
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("Get Current Weather API")
                .description("The online reference documentation for developers.<br/>"
                        + "All available Restful APIs are generated by Swagger.<br/>"
                        + "You can use it to check each API or test it on-line directly.")
                .version("1.0")
                .build();
    }

}
