server:
  port: 8000
spring:  application:    name: gcw
  jackson:    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/


logging:  file: logs/gcw.log
  level:    root: info
    org.apache.ibatis: debug
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    com.alibaba.druid.sql: debug
    com.alibaba.druid.proxy.jdbc: info
    druid.sql: info
    com.pactera.gcw: debug